server:
  port: 0

spring:
  application:
    name: first-service

eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
    instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

